In [1]:
import numpy as np

A = np.array([[1, 2],
              [4, -1]])

B = np.array([[2, -3],
              [-4, 1]])

C = np.dot(A, B) - np.dot(B, A)

print("Матрица C:")
print(C)

Матрица C:
[[ 4 -8]
 [12 -4]]


In [2]:
import numpy as np

A = np.array([[-1, 2],
              [0, 1]])

A_squared = np.dot(A, A)

print("Матрица A^2:")
print(A_squared)

Матрица A^2:
[[1 0]
 [0 1]]


In [3]:
import numpy as np

A = np.array([[3, 5],
              [6, -1]])

B = np.array([[2, 1],
              [-3, 2]])

result = np.dot(A, B)

print("Результат умножения матриц A и B:")
print(result)

Результат умножения матриц A и B:
[[-9 13]
 [15  4]]


In [4]:
import numpy as np

matrix = np.array([[2, 3, 4],
                   [1, 0, 6],
                   [7, 8, 9]])

determinant = np.linalg.det(matrix)

print("Определитель матрицы:")
print(determinant)


Определитель матрицы:
35.00000000000001


In [5]:
import numpy as np

A = np.array([[1, -2, 3],
              [4, 2, -3],
              [3, -3, 5]])

B = np.array([-5, 0, -9])

det_A = np.linalg.det(A)

Ax = A.copy()
Ax[:, 0] = B

Ay = A.copy()
Ay[:, 1] = B

Az = A.copy()
Az[:, 2] = B

det_Ax = np.linalg.det(Ax)
det_Ay = np.linalg.det(Ay)
det_Az = np.linalg.det(Az)

x = det_Ax / det_A
y = det_Ay / det_A
z = det_Az / det_A

print("Решение методом Крамера:")
print(f"x = {x}, y = {y}, z = {z}")


Решение методом Крамера:
x = -1.0, y = 1.9999999999999996, z = 0.0
